name: Check TikTok LIVE

on:
  workflow_dispatch:

  schedule:
    - cron: "*/2 * * * *"

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: node index.js

      - name: Save state
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add state.json

          git diff --cached --quiet || (
            git commit -m "Update live state"
            git push
          )
